# Site settings
title: Tom Jacobs
email: tom.jacobs@cispa.de
description: Personal webpage of Tom Jacobs
baseurl: ""
url: ""
affiliation: CISPA Helmholtz Center for Information Security

photo: c01toja.jpg
linkedin: https://www.linkedin.com/in/tom-jacobs1
github: https://github.com/tomjacobs05
scholar: https://scholar.google.com/citations?user=Yi62zDEAAAAJ

number_educ: 3
education1short: (2018-21) BSc Applied Mathematics @ TU/e
education2short: (2021-23) MSc Industrial and Applied Mathematics @ TU/e
education3short: (2024-28) PhD in ML @ CISPA Helmholtz Center for Information Security

# Google analytics ID
# google_analytics: 

# Location info. (shown in footer)
location: >
    D2 Room 1.10 <br>
    Im Oberen Werk 1 <br>
    66386 St. Ingbert (Germany)



# Contact info. (shown in footer)
# contact: >

# Pages shown in navbar
nav_pages:
  - name: publications
  - name: talks

# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

collections:
  courses:
    output: true
  publications:
    output: true
  workshops:
    output: true

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
